### ISSUE TITLE
App Tries to Start Pandora

### ISSUE THREAD

**Issue by ejohnson44** [TheLastCrusade/SoundStream#170] opened 2013-06-25 02:54 UTC
Occasionally when connecting to a network the app opens Pandora instead

**Comment by dgreenhalgh** [comment] 2013-07-03 05:08
Anyone have an idea why this is?

**Comment by theJenix** [comment] 2013-07-03 05:12
Does this happen during discovery?  Or after the host has picked a guest to connect?  Or when the guest makes itself discoverable?

-Jesse

**Comment by ejohnson44** [comment] 2013-07-05 13:10
I'm pretty positive that it happened after the host picked a guest to connect, but I haven't been able to replicate it again

**Comment by dgreenhalgh** [comment] 2013-07-07 23:13
As suggested by @reidbaker, try and get a log output for this

**Comment by theJenix** [comment] 2013-08-12 05:27
This issue is more than a month old and it doesn't sound like we can reproduce it.  I suggest we close it, and reopen if the issue happens again.  Any objection?

**Comment by reidbaker** [comment] 2013-08-13 20:18
No objection from me

On Mon, Aug 12, 2013 at 12:27 AM, Jesse Rosalia notifications@github.comwrote:

> This issue is more than a month old and it doesn't sound like we can
> reproduce it. I suggest we close it, and reopen if the issue happens again.
> Any objection?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TheLastCrusade/SoundStream/issues/170#issuecomment-22473909
> .

## 

Hamilton Reid Baker
Georgia Institute of Technology
Computer Science
Kappa Sigma
(214) 492 3163

**Comment by theJenix** [comment] 2013-08-13 21:56
@ejohnson44 Are you ok with this course of action?

**Comment by dgreenhalgh** [comment] 2013-09-05 01:05
Can't reproduce

**Closed as completed** 2013-09-05 01:05 UTC
Labels: bug
